*** Variables ***
&{ProductDataPage}
...  btnProductData=id:enterproductdata
...  txtStartDate=id:startdate
...  selInsuranceSum=id:insurancesum
...  selMeritRating=id:meritrating
...  selDamageInsurance=id:damageinsurance
...  chkOptionalProductsEuroProtection=id:EuroProtection
...  chkOptionalProductsLegalDefenseInsurance=xpath://input[@id="LegalDefenseInsurance"]/parent::label
...  selCourtesyCar=id:courtesycar
...  btnNext=id:nextselectpriceoption